apiVersion: v1
kind: Pod
metadata:
  name: http-request-testing
  labels:
    app: http-request-testing
spec:
  nodeSelector:
    cloud.google.com/machine-family: n1
  containers:
  - name: http-request-testing
    image: docker.io/bennetthardwick/http-request-testing:ubuntu-24.04@sha256:9e36ff4d74925e2da1e0258007683b0281bb22f31c7e930dfac3e79b4b8e2f63
    stdin: true 
    tty: true 
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 1
      limits:
        cpu: 1
