[package]
name = "reqwest_spawn_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
reqwest = { version = "0.12.12", features = [ "stream", "native-tls-alpn" ] }
tokio = { version = "1.42.0", features = [ "rt-multi-thread", "macros" ] }
