[package]
name = "isahc_spawn_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
isahc = "1.7.2"
tokio = { version = "1.42.0", features = [ "rt-multi-thread", "macros" ] }
tokio-util = { version = "0.7.13", features = [ "compat" ] }
